id: A8E2EF294
base_file: fE37C.txt
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-31 06:51:29.286754
  last_modified_at: 2022-05-31 06:51:29.286762
